version: "3.8"

services:
  bot:
    build:
      context: .
      shm_size: "2gb"
    container_name: gowbot
    restart: unless-stopped
    stop_grace_period: 30s
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8080')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
    user: "nobody:nogroup"
    volumes:
      # Для хранения данных SQLite
      - type: bind
        source: ./data
        target: /app/data

      # Для файлов конфигурации
      - type: bind
        source: ./settings.json
        target: /app/settings.json
        read_only: true
      - type: bind
        source: ./settings_default.json
        target: /app/settings_default.json
        read_only: true

      # Для логов
      - type: bind
        source: ./logs
        target: /app/logs
    labels:
      - "com.docker.compose.project=gowbot"
      - "com.docker.compose.service=bot"
      - "maintainer=ldubrovina"
